{{- range $name, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $secret.namespace | default $.Release.Namespace }}
  labels:
    {{- include "cluster-core-config.labels" $ | nindent 4 }}
type: {{ $secret.type | default "Opaque" }}
{{- if and (not $secret.data) (not $secret.stringData) }}
{{ fail "Either <secret>.data or <secret>.stringData must be set." }}
{{- end }}
{{- if and $secret.data $secret.stringData }}
{{ fail "Only one of <secret>.data and <secret>.stringData can be set." }}
{{- end }}
{{- if $secret.data }}
data:
{{- range $key, $value := $secret.data }}
{{- $key | nindent 4 }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- if $secret.stringData }}
stringData: {{ $secret.stringData | toYaml | b64enc | nindent 4 }}
{{- end }}
---
{{- end }}