name: PR Checks

on:
  pull_request:

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    container: jnorwood/helm-docs:v1.14.2
    steps:
      - uses: actions/checkout@v4
      - name: Run helm-docs
        run: helm-docs --chart-search-root charts --check
