name: Release Charts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    container: ghcr.io/norwoodj/helm-docs:1.14.2
    steps:
      - uses: actions/checkout@v4
      - name: Run helm-docs
        run: helm-docs --chart-search-root charts --check

  release:
    needs: helm-docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
